### ISSUE TITLE
What about UWP apps

### ISSUE THREAD

**Issue by mdell-seradex** [JamesW75/visual-studio-project-type-guid#2]
I think it (or one) is {4FDA20D0-4CD1-4A25-AEF9-3A336590E8B8}

**Comment by JamesW75** [comment]
UWP apps are {A5A43C5B-DE2A-4C0C-9213-0A381AF9435A}

The Guid which you've given shows nowhere in Google, so think it may be the ProjectGuid (unique to your project), rather than the ProjectTypeGuid(s).

**Comment by mdell-seradex** [comment]
I tried to look at it again.  I could swear that I had grabbed the correct GUID, but either I couldn't find the same project, or more likely, you are correct, as I did find a project where what you said was true.
Sorry for the bad info.
Thank you for looking into it.
