### ISSUE TITLE
csproj file Sub type 2AA76AF3-4D9E-4AF0-B243-EB9BCDFB143B not in list

### ISSUE THREAD

**Issue by stanlyong** [JamesW75/visual-studio-project-type-guid#6]
Hi - I am trying to find the subtype 2AA76AF3-4D9E-4AF0-B243-EB9BCDFB143B

**Comment by JamesW75** [comment]
I can only find 1 other reference to that GUID, and it is in a Windows Workflow Activity Library project.

https://github.com/syrotkin/learncrm/blob/master/WorkflowActivityLibrary1/WorkflowActivityLibrary1.csproj

The guid I get creating an Activity library project is {32f31d43-81cc-4c15-9de6-3fc5453562b6}.

**Comment by JamesW75** [comment]
Additional references in GitHub point to Workflow projects, so added it as an alternate.
